functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - У товаров должна проставляться категория (выводиться тегами на карточке товара)
  - Возможность сброса фильтров для вывода всех товаров в магазине
  - Возможность вернуться с карточки товара к списку товаров с сохранением последней позиции пользователя на сайте
  - Наличие счетчика добавленных товаров у корзины 
  - В корзине должна содержаться информация о выбранном товаре
  - В фильтре цены «От-До» нельзя ввести отрицательное число
